# _*_ coding: utf-8 _*_

# Models.py can be generated by sqlacodegen(https://github.com/agronholm/sqlacodegen)

__author__ = "{{.Author}}"

from sqlalchemy import CHAR, Column, Date, DateTime, Float, ForeignKey, String, text
from sqlalchemy.dialects.mysql import INTEGER, TINYINT, VARCHAR, BIGINT
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base

from app.extensions import db

class User(db.Model):
    __tablename__ = 'User'

    id = Column(BIGINT(20), primary_key=True)
    gender = Column(VARCHAR(100), server_default=text("''"))
    province = Column(VARCHAR(100), server_default=text("''"))
    city = Column(VARCHAR(100), server_default=text("''"))